version: 2
updates:
  - package-ecosystem: gradle
    directory: /api
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: /ml-sidecar
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
